version: "3.8"

services:
  avito-test-task:
    build: ./
    command: ./avito-test-task
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
  db:
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: db
    expose:
      - "3306"
    ports:
      - "3308:3306"
    environment:
      MYSQL_PASSWORD: "1234"
      MYSQL_USER: "user"
      MYSQL_DATABASE: "avito_db"
      MYSQL_ROOT_PASSWORD: "1234"
    restart: always